### ISSUE TITLE
Bug - Searchbox dismiss UI

### ISSUE THREAD

**Issue by KurosakiKST** [KyawTheMonkey/PhayarSar#1]
## Bug Report

**Description:**
User cannot go back to home screen after clicking multiple times on search

**Steps to Reproduce:**
1. Click the search icon on home screen for 3-5 times repeatedly
2. The animation between dismiss icon and search icon will overlap and user now cannot go back to home and stuck in search screen.

**Screenshot:**
![Simulator Screenshot - iPhone 15 Pro - 2024-05-08 at 14 42 14](https://github.com/kyaw-codes/PhayarSar/assets/28829665/f416f952-4c3f-4476-a74c-f30565d4e236)

**Environment:**
- Operating System: iOS Simulator
- Version/Commit of the software: Main Branch : c980aa5f612c353ca65156a867e0785a101dbb6f

**Additional Information:**
Just a small minor UI animation bug but I'd feel like reporting it since it breaks the user experience quite a bit.

**Comment by KyawTheMonkey** [comment]
Thank you so much for reporting it. I will look into that and fix the bug.

**Comment by KyawTheMonkey** [comment]
Hello @KurosakiKST, I would like to inform you that the issue you reported has been fixed and will be included in v1.1. You can check out the updated code in bug-fix branch.
